Apps/Trabajador/urls.py
from django.conf.urls import patterns, include, url
from .views import *
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'get_trabajadores', TrabajadoresViewSet)
router.register(r'get_vacaciones', VacacionesTrabajadorViewSet)
router.register(r'get_trabajador_area_cargo', TrabajadorAreaCargoViewSet)
router.register(r'get_vacaciones_trabajador', VacacionesTrabajadorReporteViewSet)
router.register(r'get_anios_vacaciones',  Anios_Vacaciones_ViewSet)
router.register(r'get_anios', AnioViewSet)

urlpatterns = patterns('',
	url(r'^', include(router.urls)),
	url(r'^lista_trabajadores/', index_trabajador.as_view(), name='Trabajador'),
	url(r'^prueba/', prueba.as_view(), name='prueba'),
	url(r'^reportes/', reporte_trabajador.as_view(), name="reportes"),
	url(r'^periodos/', PeriodoIndex.as_view(), name="periodos"),
)

Control_Vacaciones/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT,}),
    # url(r'^integrantes/fotos/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT,}),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^areas/', include("Apps.AreaCargo.urls")),
    url(r'^licencias/', include("Apps.Licencias.urls")),
    url(r'^trabajadores/', include("Apps.Trabajador.urls")),
	url(r'^$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
)

Apps/Trabajador/models.py
# -*- encoding: utf-8 -*-

from django.db import models
from django.core.validators import RegexValidator

from Apps.AreaCargo.models import Area, Cargo

# Create your models here.
class Trabajador(models.Model):
	dni = models.CharField(primary_key=True, max_length=8, validators=[
			RegexValidator(
				regex='^\d{8}$',
				message='el DNI contiene 8 digitos',
			)]
		)
	nombres = models.CharField(max_length=50)
	ap_paterno = models.CharField(max_length=50)
	ap_materno = models.CharField(max_length=50)
	email = models.EmailField(null=True, blank=True)
	direccion = models.CharField(max_length=300, null=True, blank=True)
	telefono = models.CharField(max_length=12, default="000000000000", null=True)
	dias_vacaciones = models.SmallIntegerField(default=30)
	situaciones = (
        ('PERMANENTE', 'PERMANENTE'),
        ('NOMBRADO', 'NOMBRADO'),
        ('REPUESTO JUDICIAL', 'REPUESTO JUDICIAL'),
        ('OBRERO NOMBRADO', 'OBRERO NOMBRADO'),
        ('CAS', 'CAS'),
    )
	situacion = models.CharField('Situacion',max_length=50,choices=situaciones)
	foto = models.ImageField('Foto del trabajador', upload_to='Trabajadores/fotos', null=True)


	class Meta:
		verbose_name = "TRABAJADOR"
		verbose_name_plural = "Trabajadores"
		ordering = ['ap_paterno','ap_materno','nombres']

	def __str__(self):
		valor = self.ap_paterno + " " + self.ap_materno + ", " + self.nombres + " --> ("+ self.dni +")"
		return  valor

	def save(self, *args, **kwargs):
		self.nombres=self.nombres.upper()
		self.ap_paterno=self.ap_paterno.upper()
		self.ap_materno=self.ap_materno.upper()
		self.direccion=self.direccion.upper()
		self.telefono=self.telefono.upper()
		super(Trabajador, self).save(*args, **kwargs)


class Vacaciones_Trabajador(models.Model):
	trabajador = models.ForeignKey(Trabajador)
	dias_vacaciones = models.SmallIntegerField(default=30)
	dias_acumulados = models.SmallIntegerField(default=0)
	horas_acumuladas = models.SmallIntegerField(default=0)
	anio = models.SmallIntegerField(default=0,null=True)
	fecha_registro = models.DateField(auto_now_add=True)

	class Meta:
		verbose_name = "VACACIONES POR TRABAJADOR"
		verbose_name_plural = "Vacaciones por Trabajador"
		ordering = ['trabajador__dni','fecha_registro']

	def save(self, *args, **kwargs):
		# self.dias_vacaciones=self.cargo.upper()
		super(Vacaciones_Trabajador, self).save(*args, **kwargs)

	def __str__(self):
		cadena = self.trabajador.dni + " - "  + str(self.dias_vacaciones)
		return cadena

class Anio(models.Model):
	anio = models.SmallIntegerField(default=2000)

	def __str__(self):
		cadena = str(self.anio)
		return cadena

class TrabajadorAreaCargo(models.Model):
	dni = models.ForeignKey(Trabajador)
	area = area = models.CharField(max_length=60, verbose_name='Area')
	cargo = cargo = models.CharField(max_length=50)
	periodo = models.SmallIntegerField(default=2000)
	fecha_registro = models.DateField(auto_now_add=True, null=True)

	def __str__(self):
		valor = self.dni + " " + self.area+ " " + self.cargo
		return  valor

Apps/Trabajador/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, ListView, UpdateView
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from braces import views
import json
from .models import *
from .serializers import *
from rest_framework import viewsets, generics, filters
from django.http import Http404
from rest_framework.views import APIView
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
import codecs
from rest_framework import viewsets
from django.contrib.auth.decorators import login_required
# from rest_framework import permissions

# Create your views here.
# @login_required
class index_trabajador(CreateView):
	template_name= 'index_trabajador.html'
	model = Trabajador
	success_url = reverse_lazy('Trabajador')

class prueba(CreateView):
	template_name= 'prueba.html'
	model = Trabajador
	success_url = reverse_lazy('Trabajador')
	# permission_classes =(permissions.AllowAny);
# @login_required
class reporte_trabajador(CreateView):
	template_name= 'reportes.html'
	model = Trabajador
	success_url = reverse_lazy('Trabajador')
	# permission_classes =(permissions.AllowAny);
# @login_required
class nuevo_trabajador(CreateView):
	template_name= 'nuevo_trabajador.html'
	model = Trabajador
	success_url = reverse_lazy('nuevo_trabajador')
	# permission_classes =(permissions.AllowAny);
# @login_required
class TrabajadoresViewSet(viewsets.ModelViewSet):
	serializer_class = TrabajadorSerializer
	queryset = Trabajador.objects.all()
	lookup_field ='dni'
	# permission_classes =(permissions.AllowAny);

class TrabajadorAreaCargoViewSet(viewsets.ModelViewSet):
	serializer_class =  TrabajadorAreaCargoSerializer
	queryset = TrabajadorAreaCargo.objects.all()
	# lookup_field ='id'

# @login_required
class VacacionesTrabajadorViewSet(viewsets.ModelViewSet):
	serializer_class = VacacionesSerializer
	queryset=Vacaciones_Trabajador.objects.all()
	lookup_field='id'
# @login_required
class VacacionesTrabajadorReporteViewSet(viewsets.ModelViewSet):
	serializer_class = VacacionesTrabajadorSerializer
	queryset=Vacaciones_Trabajador.objects.all()
	lookup_field='id'
	# filter_fields=('trabajador','anio')

class AnioViewSet(viewsets.ModelViewSet):
	serializer_class = AnioSerializer
	model = Anio
	queryset = Anio.objects.all()
	lookup_field='id'

class PeriodoIndex(CreateView):
	template_name= 'periodos.html'
	model = Anio
	success_url = reverse_lazy('periodos')

class Anios_Vacaciones_ViewSet(viewsets.ModelViewSet):
	serializer_class = VacacionesSerializer
	queryset = Vacaciones_Trabajador.objects.all()
	lookup_field='trabajador'

Apps/Trabajador/templates/periodos.html
						{% extends "Base.html"%}
 {% block Titulo_Pagina%} <i class="fa fa-calendar"></i> Periodos{%endblock%}
{%block contenedor_principal%}

<div class="spacer" ng-app="App" ng-controller="controlador">
<div class="row">
	<div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
								<!-- Widget starts -->
		<div class="blog blog-info">
			<div class="blog-header">
				<h5 class="blog-title">	Periodos</h5>
			</div>
			<div class="blog-body">
					<form class="bv-form" novalidate="novalidate" id="movieForm" method="post">
				<!-- {% csrf_token %} -->

					<div class="form-group has-feedback">
						<div class="row">
							<div class="col-md-12">
								<input  id="periodo" class="form-control" name="area" type="text" ng-model="anio" placeholder="Digitar periodo" maxlength="8">
							</div>
						</div>
					</div>
					<button type="submit" class="btn btn-success " ng-click="GuardarPeriodo(anio)"><i class="fa fa-check"></i> Crear</button>
					<button type="submit" class="btn btn-info pull-right" data-toggle="modal" data-target="#Lista_Areas"><i class="fa fa-eye"></i> Ver Periodos</button>
					<button type="submit" class="btn btn-danger " ng-click="LimpiarPeriodo()"><i class="fa fa-close"></i> Cancelar</button>
				</form>	
			</div>
		</div>
								<!-- Widget ends -->
    </div>
</div>
<div class="modal fade" id="Lista_Areas" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-lg">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					</div>
					<div class="modal-body">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="table-responsive">
											<table class="table table-striped table-bordered table-hover no-margin">
												<tbody>
												<tr>
												<td class="total success" colspan="3" style="background-color: #D14C4D; color:#fff;">Lista de Periodos</td>
													</tr>
													<tr >
														<td>ID</td>
														<td>Periodo</td>
													</tr>
												<tr ng-repeat="periodo in anios">
														<td>
														<span class=" right-align-text">[[periodo.id]]</span></td>
														<td>
														<span class=" right-align-text">[[periodo.anio]]</span></td>
														<td>
															<button class="btn btn-sm btn-danger botonsito" ng-click="EliminarPeriodo([[periodo.id]])"><i class="fa fa-close"></i> Eliminar Elemento</button>
														</td>
													</tr>													
												</tbody>
											</table>
											<br>
										</div>	
					</div>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-danger" data-dismiss="modal">
							<i class="fa fa-times"></i> Cerrar
					    </button>
					</div>
				</div>										
			</div>
</div>
</div>

{%endblock%}

Apps/Trabajador/templates/prueba.html
{% extends "Base.html"%}
 {% block Titulo_Pagina%} <i class="fa fa-user"></i> Trabajadores{%endblock%}
{%block contenedor_principal%}
<div ng-app="App" ng-controller="controlador">

	<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
								<div class="blog blog-success no-margin">
									<div class="blog-header">
										<h5 class="blog-title">Lista de Trabajadores</h5>
									</div>
									<div class="blog-body">
									<!-- <div class="spacer"> -->
										<div class="row">
											<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
												<input type="text" class="form-control" ng-model="busqueda" placeholder="Digite DNI del trabajador que desea buscar">
											</div>
										</div>
									<!-- </div> -->
									<br>
										<div class="table-responsive">
											<table class="table table-condensed table-bordered no-margin">
												<tbody>
													<tr class="bg-info" style="color:#fff;">
														<td><strong>DNI</strong></td>
														<td><strong>Nombres</strong></td>
														<td><strong>Direccion</strong></td>
														<td><strong>Telefono</strong></td>
														<td><strong>Acciones</strong></td>
													</tr>
													<tr ng-repeat="trabajador in trabajadores | filter:busqueda">
														<td>
															[[trabajador.dni]]
														</td>
														<td>
															[[trabajador.nombres]] [[trabajador.ap_paterno]] [[trabajador.ap_materno]]
														</td>
														<td>
															[[trabajador.direccion]]
														</td>
														<td>
															[[trabajador.telf_movil]]
														</td>
														<td>
															<button class="btn btn-sm btn-success" data-toggle="modal" data-target="#detalleTrabajador" ng-click="DetalleTrabajador([[trabajador.dni]])"><i class="fa fa-reorder"></i> Ver Detalle</button> 
															<button  class="btn btn-sm btn-danger" id="danger" ng-click="EliminarTrabajador([[trabajador.dni]])"><i class="fa fa-close"></i> Eliminar</button >
														</td>
													</tr>													
												</tbody>
											</table>
										</div> 
										<br>
										<div class="row">
											<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
												<button class="btn btn-info btn" data-toggle="modal" data-target="#modalLg" ng-click="ListarCargos([[area.id]])">
													<i class="fa fa-user"></i> 
													<span class="hidden-xs">Crear Nuevo Trabajador</span>
												</button>
											</div>
										</div>
									</div>
								</div>
							</div>		
		</div>
						
</div>


<div class="modal fade" id="modalLg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-sm">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
							<h4 class="modal-title text-info" id="myModalLabel"></h4>
					</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
								<div class="blog">
									<div class="blog-header bg-info">
										<h5 class="blog-title" style="color:#fff"><i class="fa fa-user fa-2x"></i> Agregar Nuevo Trabajador</h5>
									</div>
									<div class="blog-body">
										<form action="/trabajadores/lista_trabajadores/" method="post" enctype="multipart/form-data">
							    {% csrf_token %}
							    {# {{ form.as_p }} #}
							    <div class="form-group">
									<div class="row">
										<div class="col-md-5">
							    			<input class="form-control" type="text" name="dni" placeholder="dni">
							    		</div>
									</div>
								</div>
								<div class="form-group">
									<div class="row">
										<div class="col-md-12">
										<input class="form-control" type="text" name="nombres" placeholder="nombre" value="jose">
										</div>
									</div>
								</div>
								<div class="form-group">
									<div class="row">
										<div class="col-md-12">
										<input class="form-control" type="text" name="ap_paterno" placeholder="ap" value="quispe">	</div>
									</div>
								</div>
								<div class="form-group">
									<div class="row">
										<div class="col-md-12">
							    			<input class="form-control" type="text" name="ap_materno" placeholder="am" value="perez">
							    		</div>
									</div>
								</div>
							    <div class="form-group">
									<div class="row">
										<div class="col-md-12">
							    			<input class="form-control" type="text" name="email" placeholder="email" value="monas@asdas.com">
							    		</div>
									</div>
								</div>
								<div class="form-group">
									<div class="row">
										<div class="col-md-12">
							    			<input class="form-control" type="text" name="direccion" placeholder="direccion" value="4">
							    		</div>
									</div>
								</div>
								<div class="form-group">
									<div class="row">
										<div class="col-md-12">
							   				 <input class="form-control" type="text" name="telefono" placeholder="telf_movil" value="4644563">
							    		</div>
									</div>
								</div>
								<div class="form-group">
									<div class="row">
										<div class="col-md-12">
							    		<input class="form-control" type="text" name="dias_vacaciones" placeholder="dias_vacaciones" value="3">
							    		</div>
									</div>
								</div>
								<div class="form-group">
									<div class="row">
										<div class="col-md-12">
							    		<select id="id_situacion" name="situacion">
										<option value="" selected="selected">---------</option>
										<option value="PERMANENTE">PERMANENTE</option>
										<option value="NOMBRADO">NOMBRADO</option>
										<option value="REPUESTO JUDICIAL">REPUESTO JUDICIAL</option>
										<option value="OBRERO NOMBRADO">OBRERO NOMBRADO</option>
										<option value="CAS">CAS</option>
										</select>
							    		</div>
									</div>
								</div>
								<div class="form-group">
									<div class="row">
										<div class="col-md-12">
							    			<input  type="file" name="foto" placeholder="foto">
							    		</div>
									</div>
								</div>
							    <input type="submit" value="Submit" />
						</form>	
									</div>
								</div>
							</div>
					
					<div class="modal-footer">
					</div>
				</div>										
			</div>
</div>



{%endblock%}